Repository sebascm/taxi-booking, pull requests merged in 2019-11, with the labels that each got.

#1 fix/compile
  .gitignore
  booking-service/pom.xml
  booking-service/src/main/java/com/taxibooking/booking/util/DataMapper.java
Labels: bug

#3 config/update_plugins
  booking-service/pom.xml
  pom.xml
Labels: config

#5 Added prerequisites section
  pom.xml
Labels: config, enhancement

#6 Config/spotbugs
  api-gateway/pom.xml
  booking-service/pom.xml
  config-service/pom.xml
  discovery-service/pom.xml
  location-tracking-service/pom.xml
  pom.xml
  src/main/config/spotbugs-exclude-filter.xml
Labels: config, enhancement

#9 enhancement/jacoco
  pom.xml
Labels: config, enhancement
